[package]
name = "arch_x86_64"
version = "0.1.0"

[dependencies]
bitflags = "*"
hole_list_allocator = { path = "../../alloc/hole_list_allocator"}
spin = "*"

[dependencies.x86]
default-features = false
version = "0.7.1"
